language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - coverage run tests/test_all.py
  - coverage xml
  - python-codacy-coverage -r coverage.xml
