language: python
python:
  - "3.7"
  - "3.6"

branches:
  only:
    - master
    - develop
    - release
    - develop-microsim

addons:
  sonarcloud:
    organization: "sparrow0hawk"

install:
  - pip install -r requirements.txt

script:
  - pip install -U pytest
  - python setup.py install
  - coverage run -m pytest crime_sim_toolkit/tests/
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
