language: python
python:
  - "3.7"
  - "3.6"

branches:
  only:
    - master
    - develop*
    - release-*

install:
  - pip install -r requirements.txt

script:
  - pip install -U pytest
  - python setup.py install
  - coverage run -m pytest crime_sim_toolkit/tests/
  - coverage xml
  - bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -l python -r coverage.xml

